<template><view class="edit-page safe-page"><view class="edit-shell"><view class="heading"><button @click="back">‹</button><view><text>{{ dishId ? '编辑这道菜' : '添加一道菜' }}</text><text>名字和照片，都换成你们记得住的样子</text></view></view>
  <view class="form-card v2-card"><button class="photo" :style="form.image_url?{backgroundImage:`url(${form.image_url})`}:{}" :loading="uploading" @click="pickImage"><view v-if="!form.image_url" class="photo-mark"><view/></view><text>{{ form.image_url ? '重新选择菜品照片' : '从相册或相机选择照片' }}</text></button>
    <label><text>菜品名称</text><input v-model.trim="form.name" maxlength="30" placeholder="例如：我们家的番茄炒蛋" /></label>
    <label><text>一句描述</text><textarea v-model.trim="form.description" maxlength="120" placeholder="口味、做法，或关于这道菜的小故事" /></label>
    <button class="save" :loading="saving" :disabled="saving" @click="save">{{ dishId ? '保存菜品修改' : '保存到菜单' }}</button><text class="honest">网络或保存失败时不会显示伪成功。</text>
  </view></view></view></template>
<script setup>
import { reactive,ref } from 'vue';import { onLoad } from '@dcloudio/uni-app';import api from '../../../services/api';import store,{state} from '../../../store'
const form=reactive({name:'',description:'',image_url:''});const sectionId=ref(''),dishId=ref(''),saving=ref(false),uploading=ref(false)
onLoad(async options=>{sectionId.value=options.section_id||'';dishId.value=options.dish_id||'';if(!state.current_space)await store.bootstrap();if(dishId.value){const dish=state.menus.flatMap(menu=>menu.dishes||[]).find(item=>String(item.id)===String(dishId.value));if(!dish)return uni.showToast({title:'没有找到这道菜',icon:'none'});Object.assign(form,{name:dish.name,description:dish.description||'',image_url:dish.image_url||''});sectionId.value=dish.section_id||sectionId.value}})
function toast(e){uni.showToast({title:e.message||'操作失败',icon:'none',duration:2600})}function back(){uni.navigateBack()}
async function pickImage(){try{const chosen=await new Promise((resolve,reject)=>uni.chooseImage({count:1,sizeType:['compressed'],sourceType:['album','camera'],success:resolve,fail:reject}));uploading.value=true;const data=await api.uploadAsset(state.current_space.id,chosen.tempFilePaths[0],'dish');const url=data.url||data.image_url||data.file_url||data.asset_url;if(!url)throw new Error('服务端未返回图片 URL');form.image_url=url}catch(e){if(!String(e.errMsg||'').includes('cancel'))toast(e)}finally{uploading.value=false}}
async function save(){if(!dishId.value&&!sectionId.value)return uni.showToast({title:'未找到目标栏目',icon:'none'});if(!form.name)return uni.showToast({title:'请填写菜品名称',icon:'none'});saving.value=true;try{if(dishId.value)await api.updateDish(dishId.value,{...form});else await api.createDish(state.current_space.id,sectionId.value,{...form});await store.refreshMenus();uni.showToast({title:dishId.value?'菜品已更新':'已加入菜单',icon:'success'});setTimeout(()=>uni.navigateBack(),600)}catch(e){toast(e)}finally{saving.value=false}}
</script>
<style scoped>.edit-page{min-height:100vh;background:#F8F2E8;color:#2F2925;padding:calc(18px + env(safe-area-inset-top)) 14px calc(24px + env(safe-area-inset-bottom));box-sizing:border-box}.edit-shell{max-width:650px;margin:0 auto}.heading{display:grid;grid-template-columns:40px 1fr;align-items:center;padding:5px 0 18px}.heading button{margin:0;padding:0;background:transparent;font-size:31px;text-align:left}.heading button::after{border:0}.heading text{display:block}.heading text:first-child{font-size:20px;font-weight:750}.heading text:last-child{font-size:10px;color:#81776E;margin-top:4px}.form-card{padding:19px;background:#FFFCF7}.photo{width:100%;height:210px;background:linear-gradient(135deg,#EADCCF,#DCE4D4);background-size:cover;background-position:center;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#665D56;font-size:11px;gap:11px}.photo::after{border:0}.photo-mark{width:46px;height:46px;border:2px solid #7F9B78;border-radius:50%;position:relative}.photo-mark:before,.photo-mark:after{content:'';position:absolute;background:#7F9B78;width:20px;height:2px;left:11px;top:20px}.photo-mark:after{transform:rotate(90deg)}label{display:block;margin-top:18px}label>text{display:block;font-size:11px;font-weight:650;margin:0 0 7px 2px}input,textarea{width:100%;box-sizing:border-box;border:1px solid #DDD3C8;border-radius:12px;background:#FFF;padding:0 13px;font-size:13px}input{height:45px}textarea{height:100px;padding-top:12px}.save{height:48px;line-height:48px;border-radius:14px;background:#E86F51;color:white;font-size:14px;font-weight:700;margin-top:22px}.save::after{border:0}.honest{display:block;text-align:center;color:#9B9189;font-size:9px;margin-top:8px}@media(min-width:720px){.form-card{padding:28px}.photo{height:280px}}</style>
