# Generated by Django 5.2 on 2025-06-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="家庭名称")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "家庭",
                "verbose_name_plural": "家庭",
            },
        ),
        migrations.CreateModel(
            name="WeChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="微信 openid"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=64, verbose_name="微信 session_key"),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="昵称"
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True, verbose_name="头像")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "微信用户",
                "verbose_name_plural": "微信用户",
            },
        ),
        migrations.CreateModel(
            name="SharedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=128, verbose_name="菜谱名称")),
                (
                    "share_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="分享时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享菜谱",
                "verbose_name_plural": "分享菜谱",
            },
        ),
        migrations.CreateModel(
            name="FavoriteMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_name", models.CharField(max_length=128, verbose_name="喜爱菜品")),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "喜爱菜品",
                "verbose_name_plural": "喜爱菜品",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(max_length=32, verbose_name="与家庭关系")),
                ("is_admin", models.BooleanField(default=False, verbose_name="是否为管理员")),
                (
                    "join_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="wechat_auth.family",
                        verbose_name="家庭",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "家庭成员",
                "verbose_name_plural": "家庭成员",
            },
        ),
        migrations.CreateModel(
            name="CookingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooking_date", models.DateField(verbose_name="下厨日期")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "下厨记录",
                "verbose_name_plural": "下厨记录",
            },
        ),
    ]
