# Generated by Django 5.2 on 2025-07-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wechatuser",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=128, null=True, unique=True, verbose_name="昵称"
            ),
        ),
    ]
