# Generated by Django 5.2 on 2025-07-01 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_auth", "0002_alter_wechatuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familymember",
            options={"verbose_name": "家庭成员(旧)", "verbose_name_plural": "家庭成员(旧)"},
        ),
        migrations.RemoveField(
            model_name="family",
            name="create_time",
        ),
        migrations.AddField(
            model_name="family",
            name="code_enabled",
            field=models.BooleanField(default=True, verbose_name="邀请码是否启用"),
        ),
        migrations.AddField(
            model_name="family",
            name="code_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="邀请码过期时间"),
        ),
        migrations.AddField(
            model_name="family",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="family",
            name="invite_code",
            field=models.CharField(
                default="000000", max_length=6, unique=True, verbose_name="邀请码"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="family",
            name="max_members",
            field=models.IntegerField(default=10, verbose_name="最大成员数"),
        ),
        migrations.AddField(
            model_name="family",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="favoritemeal",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wechat_auth.family",
                verbose_name="关联家庭",
            ),
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=64, verbose_name="显示角色")),
                (
                    "permission_level",
                    models.CharField(
                        choices=[("admin", "管理员"), ("member", "普通成员")],
                        default="member",
                        max_length=20,
                        verbose_name="权限级别",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="wechat_auth.family",
                        verbose_name="家庭",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "家庭成员关系",
                "verbose_name_plural": "家庭成员关系",
                "unique_together": {("user", "family")},
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taste_preferences",
                    models.JSONField(default=list, verbose_name="口味偏好"),
                ),
                ("allergies", models.JSONField(default=list, verbose_name="过敏信息")),
                ("dislikes", models.JSONField(default=list, verbose_name="不喜欢的食物")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.family",
                        verbose_name="家庭",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wechat_auth.wechatuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
                "unique_together": {("user", "family")},
            },
        ),
    ]
