# Generated by Django 5.2 on 2025-07-01 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wechat_auth",
            "0003_alter_familymember_options_remove_family_create_time_and_more",
        ),
    ]

    operations = []
