# Generated by Django 5.2 on 2025-07-01 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_auth", "0004_auto_20250701_1236"),
    ]

    operations = [
        # 为 FavoriteMeal 添加新字段
        migrations.AddField(
            model_name='favoritemeal',
            name='category',
            field=models.CharField(default='其他', max_length=64, verbose_name='菜品分类'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='count',
            field=models.IntegerField(default=1, verbose_name='制作次数'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='菜品图片'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='liked_by',
            field=models.JSONField(default=list, verbose_name='点赞的用户'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='last_cooked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后制作时间'),
        ),
        migrations.AddField(
            model_name='favoritemeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        
        # 为 CookingRecord 添加新字段
        migrations.AddField(
            model_name='cookingrecord',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='cookingrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='cookingrecord',
            name='images',
            field=models.JSONField(default=list, verbose_name='照片列表'),
        ),
        migrations.AddField(
            model_name='cookingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        
        # 添加唯一约束
        migrations.AlterUniqueTogether(
            name='favoritemeal',
            unique_together={('family', 'meal_name')},
        ),
    ]
