# Generated by Django 5.2 on 2025-07-03 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_auth", "0005_auto_20250701_1238"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cookingrecord",
            name="cooking_date",
        ),
        migrations.AddField(
            model_name="cookingrecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="记录时间"
            ),
        ),
        migrations.AddField(
            model_name="cookingrecord",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wechat_auth.family",
                verbose_name="家庭",
            ),
        ),
        migrations.AddField(
            model_name="cookingrecord",
            name="meal_name",
            field=models.CharField(default=None, max_length=128, verbose_name="菜品名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cookingrecord",
            name="participants",
            field=models.JSONField(default=list, verbose_name="参与用餐人员"),
        ),
    ]
