# Generated by Django 5.2 on 2025-07-03 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0001_initial"),
        ("wechat_auth", "0006_remove_cookingrecord_cooking_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealrequest",
            unique_together={
                ("family", "requester", "meal_item", "request_date", "meal_session")
            },
        ),
    ]
