# Generated by Django 5.2 on 2025-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0002_alter_mealrequest_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mealorderbatch",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "早餐"),
                    ("lunch", "午餐"),
                    ("dinner", "晚餐"),
                    ("snack", "零食"),
                    ("dessert", "甜品"),
                ],
                default="lunch",
                max_length=20,
                verbose_name="餐点类型",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mealcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="分类图标（支持emoji或图片URL）",
            ),
        ),
        migrations.AlterField(
            model_name="mealorderbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("confirmed", "已确认"),
                    ("cooking", "制作中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="批次状态",
            ),
        ),
    ]
