# Generated by Django 5.2.17 on 2026-09-10 02:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import v2.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "image_style",
                    models.CharField(
                        choices=[
                            ("inherit", "继承"),
                            ("cover", "满幅"),
                            ("rounded", "圆角"),
                            ("polaroid", "拍立得"),
                            ("circle", "圆形"),
                        ],
                        default="inherit",
                        max_length=16,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[v2.models.validate_string_list],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MealRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MealSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=60)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                            ("snack", "加餐"),
                        ],
                        default="dinner",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "选择中"),
                            ("confirmed", "已确认"),
                            ("cooking", "制作中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_for", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("cover_url", models.URLField(blank=True, max_length=500)),
                (
                    "image_style",
                    models.CharField(
                        choices=[
                            ("inherit", "继承"),
                            ("cover", "满幅"),
                            ("rounded", "圆角"),
                            ("polaroid", "拍立得"),
                            ("circle", "圆形"),
                        ],
                        default="inherit",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThemePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "palette",
                    models.JSONField(
                        default=dict, validators=[v2.models.validate_palette]
                    ),
                ),
                (
                    "background_type",
                    models.CharField(
                        choices=[("color", "纯色"), ("gradient", "渐变"), ("image", "图片")],
                        default="color",
                        max_length=16,
                    ),
                ),
                ("background_value", models.CharField(blank=True, max_length=500)),
                (
                    "card_style",
                    models.CharField(
                        choices=[("solid", "实色"), ("soft", "柔和"), ("glass", "毛玻璃")],
                        default="soft",
                        max_length=16,
                    ),
                ),
                (
                    "corner_radius",
                    models.PositiveSmallIntegerField(
                        default=16,
                        validators=[django.core.validators.MaxValueValidator(32)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "wechat_openid",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", v2.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealRecordItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_items",
                        to="v2.dish",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="v2.mealrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="record",
                to="v2.mealsession",
            ),
        ),
        migrations.CreateModel(
            name="MealPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_items",
                        to="v2.dish",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="v2.mealsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "创建者"), ("member", "成员")],
                        default="member",
                        max_length=12,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=30)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                (
                    "avatar_frame",
                    models.CharField(
                        choices=[
                            ("none", "无"),
                            ("heart", "爱心"),
                            ("ring", "圆环"),
                            ("floral", "花朵"),
                            ("pixel", "像素"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("accent_color", models.CharField(blank=True, max_length=7)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mealsession",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_sessions",
                to="v2.membership",
            ),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="completed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="completed_records",
                to="v2.membership",
            ),
        ),
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("icon", models.CharField(blank=True, max_length=24)),
                ("accent_color", models.CharField(blank=True, max_length=7)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="v2.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="v2.menusection",
            ),
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[v2.models.validate_string_list],
                    ),
                ),
                (
                    "disliked_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[v2.models.validate_string_list],
                    ),
                ),
                (
                    "allergens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[v2.models.validate_string_list],
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[v2.models.validate_string_list],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="v2.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "max_members",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="v2.space",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="v2.space",
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("background", "页面背景"),
                            ("avatar", "成员头像"),
                            ("menu", "菜单封面"),
                            ("dish", "菜品图片"),
                            ("record", "用餐记录"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        height_field="height",
                        upload_to=v2.models.media_upload_path,
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="v2.space",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mealsession",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_sessions",
                to="v2.space",
            ),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_records",
                to="v2.space",
            ),
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("code_hint", models.CharField(max_length=4)),
                ("expires_at", models.DateTimeField()),
                (
                    "max_uses",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("use_count", models.PositiveSmallIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invites",
                        to="v2.membership",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="v2.space",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palette_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[v2.models.validate_palette],
                    ),
                ),
                (
                    "background_type",
                    models.CharField(
                        choices=[
                            ("preset", "跟随主题"),
                            ("color", "纯色"),
                            ("gradient", "渐变"),
                            ("image", "图片"),
                        ],
                        default="preset",
                        max_length=16,
                    ),
                ),
                ("background_value", models.CharField(blank=True, max_length=500)),
                (
                    "card_style",
                    models.CharField(
                        choices=[
                            ("preset", "跟随主题"),
                            ("solid", "实色"),
                            ("soft", "柔和"),
                            ("glass", "毛玻璃"),
                        ],
                        default="preset",
                        max_length=16,
                    ),
                ),
                (
                    "corner_radius",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(32)],
                    ),
                ),
                (
                    "menu_image_style",
                    models.CharField(
                        choices=[
                            ("cover", "满幅"),
                            ("rounded", "圆角"),
                            ("polaroid", "拍立得"),
                            ("circle", "圆形"),
                        ],
                        default="rounded",
                        max_length=16,
                    ),
                ),
                ("home_title", models.CharField(default="今天吃什么", max_length=30)),
                (
                    "navigation_labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="可覆盖 today/menu/records/us 四个导航名称",
                        validators=[v2.models.validate_navigation_labels],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "space",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance",
                        to="v2.space",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="v2.themepreset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_choices",
                        to="v2.dish",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="v2.mealsession",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_choices",
                        to="v2.membership",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "member", "dish", "custom_name"),
                        name="v2_unique_meal_choice",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("space", "account"), name="v2_unique_space_member"
            ),
        ),
    ]
