# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("v2", "0002_seed_themes")]

    operations = [
        migrations.RemoveConstraint(
            model_name="mealchoice",
            name="v2_unique_meal_choice",
        ),
        migrations.AddConstraint(
            model_name="mealchoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dish__isnull", False)),
                fields=("session", "member", "dish"),
                name="v2_unique_member_dish_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealchoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dish__isnull", True), models.Q(("custom_name", ""), _negated=True)),
                fields=("session", "member", "custom_name"),
                name="v2_unique_member_custom_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "confirmed", "cooking"])),
                fields=("space",),
                name="v2_one_active_meal_session_per_space",
            ),
        ),
    ]
